[package]
name = "reth-op-tester"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
tester-common.workspace = true

reth = { workspace = true, features = ["optimism"] }
reth-node-optimism = { workspace = true, features = ["optimism"] }

clap.workspace = true
tokio.workspace = true
