[package]
name = "reth-tester"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
tester-common.workspace = true

reth.workspace = true
reth-node-ethereum.workspace = true

clap.workspace = true
tokio.workspace = true

